Proyecto Rails/MASIVO/config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get "prueba" => "pages#prueba", as: :prueba
  get "about" => "pages#about", as: :about
  get "ranking" => "pages#ranking", as: :ranking
  get "hashtags" => "hashtags#index", as: :hashtags
  get "events" => "events#index", as: :events
  get "adminevents" => "events#index_admin", as: :adminevents

  get 'lectura_tw_stream/index'

  resources :trademarks

  resources :tweets

  resources :review_events

  resources :review_account_events

  resources :key_words_events

  resources :organizations

  resources :hashtags

  resources :events

  resources :evaluations

  resources :evaluation_account_events

  resources :data_tweet_reviews

  resources :data_evaluation_real_times

  resources :data_account_events

  resources :contacts

  resources :batch_deletions

  resources :advertises

  resources :addresses

  resources :accounts

end

Proyecto Rails/MASIVO/app/models/account.rb
class Account < ActiveRecord::Base
	has_one :data_account_event
    has_many :advertises
    has_many :tweets
    has_and_belongs_to_many :tweets #AccountTweet

	belongs_to :data_account_event 
end

Proyecto Rails/MASIVO/app/models/accounts_tweet.rb
class AccountTweet < ActiveRecord::Base
# Un tweet hace referencia a varias cuentas
   belongs_to :account
   belongs_to :tweet
end

Proyecto Rails/MASIVO/app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :organization
end

Proyecto Rails/MASIVO/app/models/advertise.rb
class Advertise < ActiveRecord::Base
	belongs_to :account
	belongs_to :event
end

Proyecto Rails/MASIVO/app/models/batch_deletion.rb
class BatchDeletion < ActiveRecord::Base
end

Proyecto Rails/MASIVO/app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :organization
end

Proyecto Rails/MASIVO/app/models/data_evaluation_real_time.rb
class DataEvaluationRealTime < ActiveRecord::Base
   has_one :evaluation 

   belongs_to :evaluation
end

Proyecto Rails/MASIVO/app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
	has_one :data_evaluation_real_time
	has_one :evaluation_account_event

	belongs_to :review_event
	belongs_to :data_evaluation_real_time
	belongs_to :evaluation_account_event
end

Proyecto Rails/MASIVO/app/models/event.rb
class Event < ActiveRecord::Base
   has_many :advertises
   has_one :review_event
   has_many :key_words_event
   has_and_belongs_to_many :organizations #EventOrganization
   has_and_belongs_to_many :hashtags #HashtagEvent
   has_and_belongs_to_many :tweets #EventTweet

   belongs_to :review_event
end

Proyecto Rails/MASIVO/app/models/event_tweet.rb
class EventTweet < ActiveRecord::Base
#Un tweet puede hacer referencia a mas de un evento
	belongs_to :event
	belongs_to :tweet
end

Proyecto Rails/MASIVO/app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
	has_and_belongs_to_many :tweets #HashtagTweet 
	has_and_belongs_to_many :events #HashtagEvent
end

Proyecto Rails/MASIVO/app/models/hashtag_event.rb
class HashtagEvent < ActiveRecord::Base
# Un hashtag puede hacer referencia a mas de un evento
	belongs_to :event
	belongs_to :hashtag
end

Proyecto Rails/MASIVO/app/models/hashtag_tweet.rb
class HashtagTweet < ActiveRecord::Base
# Un tweet puede contener mas de un hashtag
   belongs_to :hashtag
   belongs_to :tweet
end

Proyecto Rails/MASIVO/app/models/key_words_event.rb
class KeyWordsEvent < ActiveRecord::Base
	belongs_to :event
end

Proyecto Rails/MASIVO/app/models/organization.rb
class Organization < ActiveRecord::Base
	has_one :address
	has_one :contact
	has_many :trademarks
    has_and_belongs_to_many :events #EventOrganization
end

Proyecto Rails/MASIVO/app/models/review_event.rb
class ReviewEvent < ActiveRecord::Base
	has_one :event 
	has_one :review_account_event
	has_many :evaluations 

	belongs_to :event
	belongs_to :review_account_event
end

Proyecto Rails/MASIVO/app/models/trademark.rb
class Trademark < ActiveRecord::Base
	belongs_to: organization
end

Proyecto Rails/MASIVO/app/models/tweet.rb
class Tweet < ActiveRecord::Base
	has_one :data_tweet_review
    has_and_belongs_to_many :accounts #AccountTweet
    has_and_belongs_to_many :hashtags #HashtagTweet
    has_and_belongs_to_many :events #EventTweet

    belongs_to :account
    belongs_to :data_tweet_review
end

Proyecto Rails/MASIVO/app/controllers/data_evaluation_real_times_controller.rb
class DataEvaluationRealTimesController < ApplicationController
  before_action :set_data_evaluation_real_time, only: [:show, :edit, :update, :destroy]

  # GET /data_evaluation_real_times
  # GET /data_evaluation_real_times.json
  def index
    @data_evaluation_real_times = DataEvaluationRealTime.all
  end

  # GET /data_evaluation_real_times/1
  # GET /data_evaluation_real_times/1.json
  def show
  end

  # GET /data_evaluation_real_times/new
  def new
    @data_evaluation_real_time = DataEvaluationRealTime.new
  end

  # GET /data_evaluation_real_times/1/edit
  def edit
  end

  # POST /data_evaluation_real_times
  # POST /data_evaluation_real_times.json
  def create
    @data_evaluation_real_time = DataEvaluationRealTime.new(data_evaluation_real_time_params)

    respond_to do |format|
      if @data_evaluation_real_time.save
        format.html { redirect_to @data_evaluation_real_time, notice: 'Data evaluation real time was successfully created.' }
        format.json { render :show, status: :created, location: @data_evaluation_real_time }
      else
        format.html { render :new }
        format.json { render json: @data_evaluation_real_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_evaluation_real_times/1
  # PATCH/PUT /data_evaluation_real_times/1.json
  def update
    respond_to do |format|
      if @data_evaluation_real_time.update(data_evaluation_real_time_params)
        format.html { redirect_to @data_evaluation_real_time, notice: 'Data evaluation real time was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_evaluation_real_time }
      else
        format.html { render :edit }
        format.json { render json: @data_evaluation_real_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_evaluation_real_times/1
  # DELETE /data_evaluation_real_times/1.json
  def destroy
    @data_evaluation_real_time.destroy
    respond_to do |format|
      format.html { redirect_to data_evaluation_real_times_url, notice: 'Data evaluation real time was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_evaluation_real_time
      @data_evaluation_real_time = DataEvaluationRealTime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_evaluation_real_time_params
      params.require(:data_evaluation_real_time).permit(:evaluation_id)
    end
end

Proyecto Rails/MASIVO/app/helpers/data_evaluation_real_times_helper.rb
module DataEvaluationRealTimesHelper
end

Proyecto Rails/MASIVO/app/helpers/events_helper.rb
module EventsHelper
end

Proyecto Rails/MASIVO/app/helpers/pages_helper.rb
module PagesHelper
end

Proyecto Rails/MASIVO/app/helpers/tweets_helper.rb
module TweetsHelper
end

Proyecto Rails/MASIVO/app/views/data_evaluation_real_times/_form.html.erb
<%= form_for(@data_evaluation_real_time) do |f| %>
  <% if @data_evaluation_real_time.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_evaluation_real_time.errors.count, "error") %> prohibited this data_evaluation_real_time from being saved:</h2>

      <ul>
      <% @data_evaluation_real_time.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :evaluation_id %><br>
    <%= f.number_field :evaluation_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Proyecto Rails/MASIVO/app/views/data_evaluation_real_times/edit.html.erb
<h1>Editing data_evaluation_real_time</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_evaluation_real_time %> |
<%= link_to 'Back', data_evaluation_real_times_path %>

Proyecto Rails/MASIVO/app/views/data_evaluation_real_times/index.html.erb
<h1>Listing data_evaluation_real_times</h1>

<table>
  <thead>
    <tr>
      <th>Evaluation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_evaluation_real_times.each do |data_evaluation_real_time| %>
      <tr>
        <td><%= data_evaluation_real_time.evaluation_id %></td>
        <td><%= link_to 'Show', data_evaluation_real_time %></td>
        <td><%= link_to 'Edit', edit_data_evaluation_real_time_path(data_evaluation_real_time) %></td>
        <td><%= link_to 'Destroy', data_evaluation_real_time, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data evaluation real time', new_data_evaluation_real_time_path %>

Proyecto Rails/MASIVO/app/views/data_evaluation_real_times/new.html.erb
<h1>New data_evaluation_real_time</h1>

<%= render 'form' %>

<%= link_to 'Back', data_evaluation_real_times_path %>

Proyecto Rails/MASIVO/app/views/data_evaluation_real_times/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Evaluation:</strong>
  <%= @data_evaluation_real_time.evaluation_id %>
</p>

<%= link_to 'Edit', edit_data_evaluation_real_time_path(@data_evaluation_real_time) %> |
<%= link_to 'Back', data_evaluation_real_times_path %>