Proyecto Rails/MASIVO/config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get "prueba" => "pages#prueba", as: :prueba
  get "about" => "pages#about", as: :about
  get "ranking" => "pages#ranking", as: :ranking
  get "hashtags" => "hashtags#index", as: :hashtags
  get "events" => "events#index", as: :events
  get "adminevents" => "events#index_admin", as: :adminevents

  get 'lectura_tw_stream/index'

  resources :trademarks

  resources :tweets

  resources :review_events

  resources :review_account_events

  resources :key_words_events

  resources :organizations

  resources :hashtags

  resources :events

  resources :evaluations

  resources :evaluation_account_events

  resources :data_tweet_reviews

  resources :data_evaluation_real_times

  resources :data_account_events

  resources :contacts

  resources :batch_deletions

  resources :advertises

  resources :addresses

  resources :accounts

end

Proyecto Rails/MASIVO/app/models/account.rb
class Account < ActiveRecord::Base
	has_one :data_account_event
    has_many :advertises
    has_many :tweets
    has_and_belongs_to_many :tweets #AccountTweet

	belongs_to :data_account_event 
end

Proyecto Rails/MASIVO/app/models/accounts_tweet.rb
class AccountTweet < ActiveRecord::Base
# Un tweet hace referencia a varias cuentas
   belongs_to :account
   belongs_to :tweet
end

Proyecto Rails/MASIVO/app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :organization
end

Proyecto Rails/MASIVO/app/models/advertise.rb
class Advertise < ActiveRecord::Base
	belongs_to :account
	belongs_to :event
end

Proyecto Rails/MASIVO/app/models/batch_deletion.rb
class BatchDeletion < ActiveRecord::Base
end

Proyecto Rails/MASIVO/app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :organization
end

Proyecto Rails/MASIVO/app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
	has_one :data_evaluation_real_time
	has_one :evaluation_account_event

	belongs_to :review_event
	belongs_to :data_evaluation_real_time
	belongs_to :evaluation_account_event
end

Proyecto Rails/MASIVO/app/models/event.rb
class Event < ActiveRecord::Base
   has_many :advertises
   has_one :review_event
   has_many :key_words_event
   has_and_belongs_to_many :organizations #EventOrganization
   has_and_belongs_to_many :hashtags #HashtagEvent
   has_and_belongs_to_many :tweets #EventTweet

   belongs_to :review_event
end

Proyecto Rails/MASIVO/app/models/event_tweet.rb
class EventTweet < ActiveRecord::Base
#Un tweet puede hacer referencia a mas de un evento
	belongs_to :event
	belongs_to :tweet
end

Proyecto Rails/MASIVO/app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
	has_and_belongs_to_many :tweets #HashtagTweet 
	has_and_belongs_to_many :events #HashtagEvent
end

Proyecto Rails/MASIVO/app/models/hashtag_event.rb
class HashtagEvent < ActiveRecord::Base
# Un hashtag puede hacer referencia a mas de un evento
	belongs_to :event
	belongs_to :hashtag
end

Proyecto Rails/MASIVO/app/models/hashtag_tweet.rb
class HashtagTweet < ActiveRecord::Base
# Un tweet puede contener mas de un hashtag
   belongs_to :hashtag
   belongs_to :tweet
end

Proyecto Rails/MASIVO/app/models/key_words_event.rb
class KeyWordsEvent < ActiveRecord::Base
	belongs_to :event
end

Proyecto Rails/MASIVO/app/models/organization.rb
class Organization < ActiveRecord::Base
	has_one :address
	has_one :contact
	has_many :trademarks
    has_and_belongs_to_many :events #EventOrganization
end

Proyecto Rails/MASIVO/app/models/review_event.rb
class ReviewEvent < ActiveRecord::Base
	has_one :event 
	has_one :review_account_event
	has_many :evaluations 

	belongs_to :event
	belongs_to :review_account_event
end

Proyecto Rails/MASIVO/app/models/trademark.rb
class Trademark < ActiveRecord::Base
	belongs_to: organization
end

Proyecto Rails/MASIVO/app/models/tweet.rb
class Tweet < ActiveRecord::Base
	has_one :data_tweet_review
    has_and_belongs_to_many :accounts #AccountTweet
    has_and_belongs_to_many :hashtags #HashtagTweet
    has_and_belongs_to_many :events #EventTweet

    belongs_to :account
    belongs_to :data_tweet_review
end

Proyecto Rails/MASIVO/app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :set_hashtag, only: [:show, :edit, :update, :destroy]

  # GET /hashtags
  # GET /hashtags.json
  def index
    @hashtags = Hashtag.all
  end

  # GET /hashtags/1
  # GET /hashtags/1.json
  def show
  end

  # GET /hashtags/new
  def new
    @hashtag = Hashtag.new
  end

  # GET /hashtags/1/edit
  def edit
  end

  # POST /hashtags
  # POST /hashtags.json
  def create
    @hashtag = Hashtag.new(hashtag_params)

    respond_to do |format|
      if @hashtag.save
        format.html { redirect_to @hashtag, notice: 'Hashtag was successfully created.' }
        format.json { render :show, status: :created, location: @hashtag }
      else
        format.html { render :new }
        format.json { render json: @hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hashtags/1
  # PATCH/PUT /hashtags/1.json
  def update
    respond_to do |format|
      if @hashtag.update(hashtag_params)
        format.html { redirect_to @hashtag, notice: 'Hashtag was successfully updated.' }
        format.json { render :show, status: :ok, location: @hashtag }
      else
        format.html { render :edit }
        format.json { render json: @hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hashtags/1
  # DELETE /hashtags/1.json
  def destroy
    @hashtag.destroy
    respond_to do |format|
      format.html { redirect_to hashtags_url, notice: 'Hashtag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hashtag
      @hashtag = Hashtag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hashtag_params
      params.require(:hashtag).permit(:date_publish_hashtag, :official, :num_mentions_hashtag, :hashtag_content)
    end
end

Proyecto Rails/MASIVO/app/helpers/accounts_helper.rb
module AccountsHelper
end

Proyecto Rails/MASIVO/app/helpers/events_helper.rb
module EventsHelper
end

Proyecto Rails/MASIVO/app/helpers/hashtags_helper.rb
module HashtagsHelper
end

Proyecto Rails/MASIVO/app/helpers/pages_helper.rb
module PagesHelper
end

Proyecto Rails/MASIVO/app/helpers/tweets_helper.rb
module TweetsHelper
end

Proyecto Rails/MASIVO/app/views/hashtags/_form.html.erb
<%= form_for(@hashtag) do |f| %>
  <% if @hashtag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hashtag.errors.count, "error") %> prohibited this hashtag from being saved:</h2>

      <ul>
      <% @hashtag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_publish_hashtag %><br>
    <%= f.datetime_select :date_publish_hashtag %>
  </div>
  <div class="field">
    <%= f.label :official %><br>
    <%= f.check_box :official %>
  </div>
  <div class="field">
    <%= f.label :num_mentions_hashtag %><br>
    <%= f.number_field :num_mentions_hashtag %>
  </div>
  <div class="field">
    <%= f.label :hashtag_content %><br>
    <%= f.text_field :hashtag_content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Proyecto Rails/MASIVO/app/views/hashtags/edit.html.erb
<br>
<br>
<h1>Editing hashtag</h1>

<%= render 'form' %>

<%= link_to 'Show', @hashtag %> |
<%= link_to 'Back', hashtags_path %>

Proyecto Rails/MASIVO/app/views/hashtags/index.html.erb
<br>
<br>
<h1>Lista de Hashtags</h1>

<table>
  <thead>
    <tr>
      <th>Date publish hashtag</th>
      <th>Official</th>
      <th>Num mentions hashtag</th>
      <th>Hashtag content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hashtags.each do |hashtag| %>
      <tr>
        <td><%= hashtag.date_publish_hashtag %></td>
        <td><%= hashtag.official %></td>
        <td><%= hashtag.num_mentions_hashtag %></td>
        <td><%= hashtag.hashtag_content %></td>
        <td><%= link_to 'Show', hashtag %></td>
        <td><%= link_to 'Edit', edit_hashtag_path(hashtag) %></td>
        <td><%= link_to 'Destroy', hashtag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

 <div class="col-lg-2">

          <div id="canvas-holder">
          
            <canvas id="chart-area1" height="500" width="500" style="width: 818px; height: 409px;"></canvas>
          </div>
          <script>
              var data = {
    labels: [""],
    datasets: [
            <%@hashtags.each do |hashtag|%>
            {
             name: '<%= hashtag.hashtag_content%>',
             fillColor: "#E32F2F",
             strokeColor: "#E32F2F",
             highlightFill: "#E32F2F",
             highlightStroke: "#E32F2F",
             data: [<%= hashtag.num_mentions_hashtag%>]
            },
            <% end %>
                 ]
};


              var ctx = document.getElementById("chart-area1").getContext("2d");
              window.myBarChart = new Chart(ctx).Bar(data);

             </script>

<br>

<%= link_to 'New Hashtag', new_hashtag_path %>

Proyecto Rails/MASIVO/app/views/hashtags/new.html.erb
<br>
<br>
<h1>Nuevo Hashtag</h1>

<%= render 'form' %>

<%= link_to 'Back', hashtags_path %>

Proyecto Rails/MASIVO/app/views/hashtags/show.html.erb
<br>
<br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Date publish hashtag:</strong>
  <%= @hashtag.date_publish_hashtag %>
</p>

<p>
  <strong>Official:</strong>
  <%= @hashtag.official %>
</p>

<p>
  <strong>Num mentions hashtag:</strong>
  <%= @hashtag.num_mentions_hashtag %>
</p>

<p>
  <strong>Hashtag content:</strong>
  <%= @hashtag.hashtag_content %>
</p>

<%= link_to 'Edit', edit_hashtag_path(@hashtag) %> |
<%= link_to 'Back', hashtags_path %>

  <div id="canvas-holder">
          
            <canvas id="chart-area1" height="300" width="300" style="width: 818px; height: 409px;"></canvas>
          </div>
          <script>
              var data = {
    labels: [""],
    datasets: [
            
            {
             name: '<%= @hashtag.hashtag_content %>',
             fillColor: "#E32F2F",
             strokeColor: "#E32F2F",
             highlightFill: "#E32F2F",
             highlightStroke: "#E32F2F",
             data: [<%= @hashtag.num_mentions_hashtag%>]
            },
           
                 ]
};


              var ctx = document.getElementById("chart-area1").getContext("2d");
              window.myBarChart = new Chart(ctx).Bar(data);

             </script>