Proyecto Rails/MASIVO/config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get "prueba" => "pages#prueba", as: :prueba
  get "about" => "pages#about", as: :about
  get "ranking" => "pages#ranking", as: :ranking
  get "hashtags" => "hashtags#index", as: :hashtags
  get "events" => "events#index", as: :events
  get "adminevents" => "events#index_admin", as: :adminevents

  get 'lectura_tw_stream/index'

  resources :trademarks

  resources :tweets

  resources :review_events

  resources :review_account_events

  resources :key_words_events

  resources :organizations

  resources :hashtags

  resources :events

  resources :evaluations

  resources :evaluation_account_events

  resources :data_tweet_reviews

  resources :data_evaluation_real_times

  resources :data_account_events

  resources :contacts

  resources :batch_deletions

  resources :advertises

  resources :addresses

  resources :accounts

end

Proyecto Rails/MASIVO/app/models/account.rb
class Account < ActiveRecord::Base
	has_one :data_account_event
    has_many :advertises
    has_many :tweets
    has_and_belongs_to_many :tweets #AccountTweet

	belongs_to :data_account_event 
end

Proyecto Rails/MASIVO/app/models/accounts_tweet.rb
class AccountTweet < ActiveRecord::Base
# Un tweet hace referencia a varias cuentas
   belongs_to :account
   belongs_to :tweet
end

Proyecto Rails/MASIVO/app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :organization
end

Proyecto Rails/MASIVO/app/models/advertise.rb
class Advertise < ActiveRecord::Base
	belongs_to :account
	belongs_to :event
end

Proyecto Rails/MASIVO/app/models/batch_deletion.rb
class BatchDeletion < ActiveRecord::Base
end

Proyecto Rails/MASIVO/app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :organization
end

Proyecto Rails/MASIVO/app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
	has_one :data_evaluation_real_time
	has_one :evaluation_account_event

	belongs_to :review_event
	belongs_to :data_evaluation_real_time
	belongs_to :evaluation_account_event
end

Proyecto Rails/MASIVO/app/models/event.rb
class Event < ActiveRecord::Base
   has_many :advertises
   has_one :review_event
   has_many :key_words_event
   has_and_belongs_to_many :organizations #EventOrganization
   has_and_belongs_to_many :hashtags #HashtagEvent
   has_and_belongs_to_many :tweets #EventTweet

   belongs_to :review_event
end

Proyecto Rails/MASIVO/app/models/event_tweet.rb
class EventTweet < ActiveRecord::Base
#Un tweet puede hacer referencia a mas de un evento
	belongs_to :event
	belongs_to :tweet
end

Proyecto Rails/MASIVO/app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
	has_and_belongs_to_many :tweets #HashtagTweet 
	has_and_belongs_to_many :events #HashtagEvent
end

Proyecto Rails/MASIVO/app/models/hashtag_event.rb
class HashtagEvent < ActiveRecord::Base
# Un hashtag puede hacer referencia a mas de un evento
	belongs_to :event
	belongs_to :hashtag
end

Proyecto Rails/MASIVO/app/models/hashtag_tweet.rb
class HashtagTweet < ActiveRecord::Base
# Un tweet puede contener mas de un hashtag
   belongs_to :hashtag
   belongs_to :tweet
end

Proyecto Rails/MASIVO/app/models/key_words_event.rb
class KeyWordsEvent < ActiveRecord::Base
	belongs_to :event
end

Proyecto Rails/MASIVO/app/models/organization.rb
class Organization < ActiveRecord::Base
	has_one :address
	has_one :contact
	has_many :trademarks
    has_and_belongs_to_many :events #EventOrganization
end

Proyecto Rails/MASIVO/app/models/review_event.rb
class ReviewEvent < ActiveRecord::Base
	has_one :event 
	has_one :review_account_event
	has_many :evaluations 

	belongs_to :event
	belongs_to :review_account_event
end

Proyecto Rails/MASIVO/app/models/trademark.rb
class Trademark < ActiveRecord::Base
	belongs_to: organization
end

Proyecto Rails/MASIVO/app/models/tweet.rb
class Tweet < ActiveRecord::Base
	has_one :data_tweet_review
    has_and_belongs_to_many :accounts #AccountTweet
    has_and_belongs_to_many :hashtags #HashtagTweet
    has_and_belongs_to_many :events #EventTweet

    belongs_to :account
    belongs_to :data_tweet_review
end

Proyecto Rails/MASIVO/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name_organization, :url_organization)
    end
end

Proyecto Rails/MASIVO/app/helpers/accounts_helper.rb
module AccountsHelper
end

Proyecto Rails/MASIVO/app/helpers/events_helper.rb
module EventsHelper
end

Proyecto Rails/MASIVO/app/helpers/organizations_helper.rb
module OrganizationsHelper
end

Proyecto Rails/MASIVO/app/helpers/pages_helper.rb
module PagesHelper
end

Proyecto Rails/MASIVO/app/helpers/tweets_helper.rb
module TweetsHelper
end

Proyecto Rails/MASIVO/app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_organization %><br>
    <%= f.text_field :name_organization %>
  </div>
  <div class="field">
    <%= f.label :url_organization %><br>
    <%= f.text_field :url_organization %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Proyecto Rails/MASIVO/app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

Proyecto Rails/MASIVO/app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name organization</th>
      <th>Url organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name_organization %></td>
        <td><%= organization.url_organization %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

Proyecto Rails/MASIVO/app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

Proyecto Rails/MASIVO/app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name organization:</strong>
  <%= @organization.name_organization %>
</p>

<p>
  <strong>Url organization:</strong>
  <%= @organization.url_organization %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>